In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/developer_survey_2019/survey_results_public.csv')

In [3]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [4]:
df.shape

(88883, 85)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [6]:
# How many columns do you want.
pd.set_option('display.max_columns', 85)

In [7]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [8]:
schema_df = pd.read_csv('data/developer_survey_2019/survey_results_schema.csv')

In [9]:
schema_df

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [10]:
df.tail()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [11]:
# Using this as a sample ==> dfs (data frame sample)

people = {
    "first" : ["Sam", "Pete", "Sara"],
    "last" : ["Nelson", "Nelson","Green"],
    "email" : ["sam@gmail.com", "pete@gmail.com","sara@hotmail.com"],
}

In [12]:
dfs = pd.DataFrame(people)
dfs

  first    last             email
0   Sam  Nelson     sam@gmail.com
1  Pete  Nelson    pete@gmail.com
2  Sara   Green  sara@hotmail.com

In [13]:
dfs['email'], type(dfs['email'])

(0       sam@gmail.com
 1      pete@gmail.com
 2    sara@hotmail.com
 Name: email, dtype: object,
 pandas.core.series.Series)

In [14]:
dfs.email

0       sam@gmail.com
1      pete@gmail.com
2    sara@hotmail.com
Name: email, dtype: object

In [15]:
dfs.count()

first    3
last     3
email    3
dtype: int64

In [16]:
dfs[['first', 'last']]

  first    last
0   Sam  Nelson
1  Pete  Nelson
2  Sara   Green

In [17]:
dfs.columns

Index(['first', 'last', 'email'], dtype='object')

In [18]:
# loc ==> location
# iloc ==> integer location

In [19]:
dfs.iloc[0]  # Gives first row.

first              Sam
last            Nelson
email    sam@gmail.com
Name: 0, dtype: object

In [20]:
dfs.iloc[0]['first'] , type(dfs.iloc[0]['first'])

('Sam', str)

In [21]:
dfs.iloc[[0, 1]]

  first    last           email
0   Sam  Nelson   sam@gmail.com
1  Pete  Nelson  pete@gmail.com

In [22]:
dfs.iloc[[0, 1], 0]

0     Sam
1    Pete
Name: first, dtype: object

In [23]:
dfs.iloc[[0, 1], [0, 2]]

  first           email
0   Sam   sam@gmail.com
1  Pete  pete@gmail.com

In [24]:
df.shape

(88883, 85)

In [25]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [26]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [27]:
df['OpenSource'].value_counts()

The quality of OSS and closed source software is about the same                    41527
OSS is, on average, of HIGHER quality than proprietary / closed source software    36556
OSS is, on average, of LOWER quality than proprietary / closed source software      8759
Name: OpenSource, dtype: int64

In [28]:
df.loc[0] # 0 is the name of the row index, loc does not work with indeces.

Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object

In [29]:
df.loc[0, 'Hobbyist']

'Yes'

In [30]:
df.loc[0:5, 'Employment' : 'Student'] # Note slicing is inclusive.

,Employment,Country,Student
0,"Not employed, and not looking for work",United Kingdom,No
1,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time"
2,Employed full-time,Thailand,No
3,Employed full-time,United States,No
4,Employed full-time,Ukraine,No
5,Employed full-time,Canada,No

In [31]:
df.loc[[0,1,2], ['Employment', 'Student']]

                               Employment         Student
0  Not employed, and not looking for work              No
1      Not employed, but looking for work  Yes, full-time
2                      Employed full-time              No

Going back to dfs.

In [32]:
dfs

  first    last             email
0   Sam  Nelson     sam@gmail.com
1  Pete  Nelson    pete@gmail.com
2  Sara   Green  sara@hotmail.com

In [33]:
dfs.set_index('email', inplace=True)

In [34]:
dfs

                 first    last
email
sam@gmail.com      Sam  Nelson
pete@gmail.com    Pete  Nelson
sara@hotmail.com  Sara   Green

In [35]:
dfs.index

Index(['sam@gmail.com', 'pete@gmail.com', 'sara@hotmail.com'], dtype='object', name='email')

In [36]:
dfs.loc['sam@gmail.com']

first       Sam
last     Nelson
Name: sam@gmail.com, dtype: object

In [37]:
dfs.reset_index(inplace=True)
dfs

              email first    last
0     sam@gmail.com   Sam  Nelson
1    pete@gmail.com  Pete  Nelson
2  sara@hotmail.com  Sara   Green

In [38]:
df = pd.read_csv('data/developer_survey_2019/survey_results_public.csv', index_col='Respondent')  # Setting the index when reading the file.
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [39]:
schema_df = pd.read_csv('data/developer_survey_2019/survey_results_schema.csv', index_col='Column')
schema_df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [40]:
schema_df.loc['MgrIdiot','QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [41]:
schema_df.sort_index()  # because there is no inplace = True this is not changing the actual dataframe.s

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]

In [42]:
schema_df.sort_index(ascending=False)

                                                    QuestionText
Column
YearsCodePro   How many years have you coded professionally (...
YearsCode      Including any education, how many years have y...
WorkWeekHrs     On average, how many hours per week do you work?
WorkRemote                       How often do you work remotely?
WorkPlan                 How structured or planned is your work?
...                                                          ...
BlockchainOrg  How is your organization thinking about or imp...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BetterLife     Do you think people born today will have a bet...
Age1stCode     At what age did you write your first line of c...
Age            What is your age (in years)? If you prefer not...

[85 rows x 1 columns]

In [43]:
dfs

              email first    last
0     sam@gmail.com   Sam  Nelson
1    pete@gmail.com  Pete  Nelson
2  sara@hotmail.com  Sara   Green

In [44]:
dfs['last'] == 'Nelson'

0     True
1     True
2    False
Name: last, dtype: bool

In [45]:
mask = dfs['last'] == 'Nelson'

In [46]:
dfs[mask]

            email first    last
0   sam@gmail.com   Sam  Nelson
1  pete@gmail.com  Pete  Nelson

In [47]:
dfs.loc[mask]

            email first    last
0   sam@gmail.com   Sam  Nelson
1  pete@gmail.com  Pete  Nelson

In [48]:
dfs.loc[(dfs['last'] == 'Nelson') & (dfs['first'] == 'Sam')]

           email first    last
0  sam@gmail.com   Sam  Nelson

In [49]:
dfs.loc[(dfs['last'] == 'Nelson') & (dfs['first'] == 'Sam'), ['first', 'last']] # Example ==> AND &

  first    last
0   Sam  Nelson

In [50]:
dfs.loc[(dfs['last'] == 'Nelson') | (dfs['first'] == 'Sam'), ['first', 'last']] # Example ==> OR |

  first    last
0   Sam  Nelson
1  Pete  Nelson

In [51]:
dfs.loc[~(dfs['last'] == 'Nelson') , ['first', 'last']]  # Not ~

  first   last
2  Sara  Green

In [52]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [53]:
# High Salary
df.loc[df['ConvertedComp'] > 70000, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88882,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [54]:
countries = ['United States', "India", "Germany", "Canada"]

In [55]:
country_filter = df['Country'].isin(countries)
country_filter

Respondent
1        False
2        False
3        False
4         True
5        False
         ...
88377     True
88601    False
88802    False
88816    False
88863    False
Name: Country, Length: 88883, dtype: bool

In [56]:
df.loc[(df['ConvertedComp'] > 70000), ['Country', 'LanguageWorkedWith', 'ConvertedComp']].loc[country_filter]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
26,United States,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,114000.0
29,United States,Bash/Shell/PowerShell;JavaScript;SQL,100000.0
...,...,...,...
88873,Canada,HTML/CSS;JavaScript;PHP;Python;R;SQL,72522.0
88874,United States,C++;Python;Scala;SQL,2000000.0
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0

In [57]:
df.loc[(df['ConvertedComp'] > 70000) & country_filter, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
26,United States,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,114000.0
29,United States,Bash/Shell/PowerShell;JavaScript;SQL,100000.0
...,...,...,...
88873,Canada,HTML/CSS;JavaScript;PHP;Python;R;SQL,72522.0
88874,United States,C++;Python;Scala;SQL,2000000.0
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0

In [58]:
df.loc[(df['ConvertedComp'] > 70000) & country_filter, ['Country', 'LanguageWorkedWith', 'ConvertedComp']].loc[:,'Country']

Respondent
6               Canada
13       United States
22       United States
26       United States
29       United States
             ...
88873           Canada
88874    United States
88876    United States
88877    United States
88878    United States
Name: Country, Length: 14895, dtype: object

In [59]:
df.loc[(df['ConvertedComp'] > 70000) & country_filter, ['Country', 'LanguageWorkedWith', 'ConvertedComp']].loc[:,'Country'].value_counts()

United States    12192
Germany           1386
Canada            1062
India              255
Name: Country, dtype: int64

In [60]:
# People who have worked with Python
filt =df['LanguageWorkedWith'].str.contains('Python', na='False')
filt

Respondent
1         True
2         True
3        False
4         True
5         True
         ...
88377    False
88601    False
88802    False
88816    False
88863    False
Name: LanguageWorkedWith, Length: 88883, dtype: object

In [61]:
# Adding Python Filter
df.loc[(df['ConvertedComp'] > 70000) & country_filter & filt, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
26,United States,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,114000.0
32,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,1100000.0
45,United States,Python,175000.0
60,United States,Bash/Shell/PowerShell;Go;JavaScript;PHP;Python...,107000.0
...,...,...,...
88839,United States,HTML/CSS;JavaScript;PHP;Python;SQL;Other(s):,95000.0
88861,Germany,Go;HTML/CSS;JavaScript;PHP;Python;SQL,97389.0
88873,Canada,HTML/CSS;JavaScript;PHP;Python;R;SQL,72522.0
88874,United States,C++;Python;Scala;SQL,2000000.0
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0

---

__Updating data__

In [62]:
people = {
    "first" : ["Sam", "Pete", "Sara"],
    "last" : ["Nelson", "Nelson","Green"],
    "email" : ["sam@gmail.com", "pete@gmail.com","sara@hotmail.com"],
}
dfs = pd.DataFrame(people)
dfs

  first    last             email
0   Sam  Nelson     sam@gmail.com
1  Pete  Nelson    pete@gmail.com
2  Sara   Green  sara@hotmail.com

In [63]:
dfs.columns = ['first_name', 'last_name', 'email']
dfs

  first_name last_name             email
0        Sam    Nelson     sam@gmail.com
1       Pete    Nelson    pete@gmail.com
2       Sara     Green  sara@hotmail.com

In [65]:
dfs.columns = [x.upper() for x in dfs.columns]
dfs

  FIRST_NAME LAST_NAME             EMAIL
0        Sam    Nelson     sam@gmail.com
1       Pete    Nelson    pete@gmail.com
2       Sara     Green  sara@hotmail.com

In [67]:
dfs.columns = ['first name', 'last name', 'email']
dfs

  first name last name             email
0        Sam    Nelson     sam@gmail.com
1       Pete    Nelson    pete@gmail.com
2       Sara     Green  sara@hotmail.com

In [69]:
dfs.columns = dfs.columns.str.replace(' ','_')
dfs

  first_name last_name             email
0        Sam    Nelson     sam@gmail.com
1       Pete    Nelson    pete@gmail.com
2       Sara     Green  sara@hotmail.com

In [71]:
dfs.rename(columns= {'first_name' : 'first'}, inplace=True)
dfs

  first last_name             email
0   Sam    Nelson     sam@gmail.com
1  Pete    Nelson    pete@gmail.com
2  Sara     Green  sara@hotmail.com

In [72]:
dfs.rename(columns= {'last_name' : 'last'}, inplace=True)
dfs

  first    last             email
0   Sam  Nelson     sam@gmail.com
1  Pete  Nelson    pete@gmail.com
2  Sara   Green  sara@hotmail.com

In [76]:
# Updating values for all cols of a row.
dfs.loc[2] = ['Sara', 'Green', 'sara@yahoomail.com']
dfs

  first    last               email
0   Sam  Nelson       sam@gmail.com
1  Pete  Nelson      pete@gmail.com
2  Sara   Green  sara@yahoomail.com

In [78]:
# Updating values for certain cols of a row.
dfs.loc[2, ['first', 'email']] = ['Sarah', 'sarah@yahoomail.com']
dfs

   first    last                email
0    Sam  Nelson        sam@gmail.com
1   Pete  Nelson       pete@gmail.com
2  Sarah   Green  sarah@yahoomail.com

In [79]:
dfs.loc[2, 'email'] =  'sarah@live.com'
dfs

   first    last           email
0    Sam  Nelson   sam@gmail.com
1   Pete  Nelson  pete@gmail.com
2  Sarah   Green  sarah@live.com

In [82]:
dfs.at[2, 'email'] =  'sarah@zoho.com'   # .at Access a single value for a row/column label pair.
dfs

   first    last           email
0    Sam  Nelson   sam@gmail.com
1   Pete  Nelson  pete@gmail.com
2  Sarah   Green  sarah@zoho.com

Updating multiple rows of data.

In [87]:
dfs['email'] = dfs.loc[:,'email'].str.upper()
dfs

   first    last           email
0    Sam  Nelson   SAM@GMAIL.COM
1   Pete  Nelson  PETE@GMAIL.COM
2  Sarah   Green  SARAH@ZOHO.COM

Replacing values are done using the following common methods.

- apply
- map
- applymap
- replace

__apply__